#!/bin/sh
#
# Fanctl application
#
case "$1" in
  start)
	insmod /usr/lib/fanctl.ko
  	/usr/bin/fanctl_daemon &
	echo "fanctl_daemon application launched"
	;;
  stop)
  	killall fanctl_daemon
	rmmod fanctl
	echo "fanctl_daemon application stopped"
	;;
  restart|reload)
    $0 stop
    $0 start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

